/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pegaso.desktop;

import org.junit.Test;
import es.mde.pegasodesktop.App;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
